const gate=document.querySelector('.gate'),cinema=document.querySelector('.cinema'),story=document.querySelector('.story'),chapters=[...document.querySelectorAll('.chapter')],progress=document.querySelector('.story-progress'),progressBar=progress.querySelector('span'),audio=document.querySelector('#birthday-song'),soundButton=document.querySelector('.sound');let current=0,changing=false,introTimer,fadeFrame;
function setScene(from,to){from.classList.remove('is-active');from.setAttribute('aria-hidden','true');to.classList.add('is-active');to.setAttribute('aria-hidden','false')}
function makeCelebration(){const layer=document.querySelector('.falling-things');layer.innerHTML='';const pieces=['♡','♥','●','✦'];for(let i=0;i<58;i++){const p=document.createElement('i');p.textContent=pieces[i%4];p.style.left=`${Math.random()*100}%`;p.style.color=['#ed1b2f','#fff4df','#edb83a','#f7a1b5'][i%4];p.style.fontSize=`${10+Math.random()*18}px`;p.style.setProperty('--duration',`${4+Math.random()*4}s`);p.style.setProperty('--delay',`${2.2+Math.random()*3}s`);p.style.setProperty('--drift',`${-90+Math.random()*180}px`);layer.appendChild(p)}}
function beginStory(){clearTimeout(introTimer);cinema.classList.remove('is-playing');setScene(cinema,story);progress.classList.add('is-visible');current=0;chapters.forEach((c,i)=>c.classList.toggle('is-active',i===0));progressBar.style.width='20%'}
async function startFilm(){cancelAnimationFrame(fadeFrame);audio.volume=1;setScene(gate,cinema);makeCelebration();requestAnimationFrame(()=>cinema.classList.add('is-playing'));try{await audio.play();soundButton.classList.add('is-playing');soundButton.setAttribute('aria-pressed','true');soundButton.querySelector('b').textContent='sound off'}catch{}introTimer=setTimeout(beginStory,11200)}
function showChapter(index){if(changing||index<0||index>=chapters.length||index===current)return;changing=true;const out=chapters[current],incoming=chapters[index];out.classList.add('is-leaving');out.classList.remove('is-active');incoming.classList.add('is-active');current=index;progressBar.style.width=`${((current+1)/chapters.length)*100}%`;setTimeout(()=>{out.classList.remove('is-leaving');changing=false},780)}
function replay(){clearTimeout(introTimer);progress.classList.remove('is-visible');progressBar.style.width='20%';cinema.classList.remove('is-playing','is-active');cinema.setAttribute('aria-hidden','true');document.querySelector('.falling-things').innerHTML='';setScene(story,gate);current=0;changing=false;chapters.forEach((c,i)=>{c.classList.remove('is-leaving');c.classList.toggle('is-active',i===0)});const started=performance.now(),startVolume=audio.volume;function finishAudioReset(){audio.pause();audio.currentTime=0;audio.volume=1;soundButton.classList.remove('is-playing');soundButton.setAttribute('aria-pressed','false');soundButton.querySelector('b').textContent='sound on'}function fade(now){const amount=Math.min((now-started)/1100,1);audio.volume=Math.max(0,startVolume*(1-amount));if(amount<1&&!audio.paused){fadeFrame=requestAnimationFrame(fade)}else{finishAudioReset()}}if(audio.paused){finishAudioReset()}else{fadeFrame=requestAnimationFrame(fade)}}
document.querySelector('.admit').addEventListener('click',startFilm);document.querySelector('.skip-intro').addEventListener('click',beginStory);document.querySelectorAll('.next').forEach(b=>b.addEventListener('click',()=>showChapter(current+1)));document.querySelector('.replay').addEventListener('click',replay);
soundButton.addEventListener('click',async()=>{const label=soundButton.querySelector('b');if(audio.paused){try{await audio.play();soundButton.classList.add('is-playing');soundButton.setAttribute('aria-pressed','true');label.textContent='sound off'}catch{label.textContent='add song.mp3'}}else{audio.pause();soundButton.classList.remove('is-playing');soundButton.setAttribute('aria-pressed','false');label.textContent='sound on'}});
document.addEventListener('keydown',e=>{if(!story.classList.contains('is-active'))return;if(['ArrowRight','Enter',' '].includes(e.key))showChapter(current+1);if(e.key==='ArrowLeft')showChapter(current-1)});let touchX=0;story.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].screenX},{passive:true});story.addEventListener('touchend',e=>{const d=e.changedTouches[0].screenX-touchX;if(Math.abs(d)>55)showChapter(current+(d<0?1:-1))},{passive:true});
